[package]
name = "list_stats"
version = "0.1.0"
authors = ["plyq <xanatos.shubunkin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compare = "0.1.0"
 
